### ISSUE TITLE
[maven-release-plugin] Consolidate git push

### ISSUE THREAD

**Issue by mkarg** [github/maven-plugins#116]
mvn release:prepare runs three times git push which is bad:
- A single push at the end is enough to bring all commits and tags to the server finally
- It consumes more time than essentially necessary
- It is risky, because in case the first POM change A-SNAPSHOT -> A is pushed to the server but an error happens (bug in plugin, crash of client, whatever) then a "half prepared" state is on the server (the second POM change A -> B-SNAPSHOT is missing) and you cannot auto-recover from that without manual action (as mvn release:clean does not undo the tag). If there is only one single push at the end, then EVERYTHING, two commits and a tag, is pushed as a single transaction to the server, which is much better!

**Comment by mprins** [comment]
this is not the place for your issue, talk to the release plugin people

**Comment by mkarg** [comment]
I see. So only code is mirrored but issue tracker is not?

**Comment by mprins** [comment]
It seems you never checked the code, this plugin does something different, not release.

**Comment by mkarg** [comment]
Darn, right! I actually wanted to report at https://github.com/apache/maven-plugins actually. Thanks!
