### ISSUE TITLE
Error creating blob: Not Found (404)

### ISSUE THREAD

**Issue by Dilitand1** [github/maven-plugins#145]
i taking error: Failed to execute goal com.github.github:site-maven-plugin:0.12:site (default) on project mavenRepoTest: Error creating blob: Not Found (404) -> [Help 1]

**Comment by Dilitand1** [comment]
the reason was a using password instead token...

**Comment by Dilitand1** [comment]
the reason was a using password instead token...

**Comment by HyperCodec** [comment]
Getting the same error at the same point, but I *am* using a token
