### ISSUE TITLE
Failed to execute goal com.github.github:downloads-maven-plugin:0.6:upload (default) on project github-maven-example:

### ISSUE THREAD

**Issue by waqassadiq** [github/maven-plugins#41]
I was working with sample maven project from eclipse.
on running install, i am getting this error.
clean, build and test commands are working fine.

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.github.kevinsawicki:github-maven-example:jar:0.1-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-javadoc-plugin is missing. @ line 135, column 12
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ line 115, column 12
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-source-plugin is missing. @ line 146, column 12
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-jar-plugin is missing. @ line 123, column 12
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO]  
[INFO] ------------------------------------------------------------------------
[INFO] Building GitHub Maven Plugin Example 0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.5:resources (default-resources) @ github-maven-example ---
[debug] execute contextualize
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory D:\qasibeat\temp-workspace\git\example\src\main\resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ github-maven-example ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.5:testResources (default-testResources) @ github-maven-example ---
[debug] execute contextualize
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory D:\qasibeat\temp-workspace\git\example\src\test\resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:testCompile (default-testCompile) @ github-maven-example ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:2.10:test (default-test) @ github-maven-example ---
[INFO] Surefire report directory: D:\qasibeat\temp-workspace\git\example\target\surefire-reports

---
##  T E S T S

Running com.github.maven.example.tests.WidgetTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.03 sec

Results :

Tests run: 2, Failures: 0, Errors: 0, Skipped: 0

[INFO] 
[INFO] --- maven-jar-plugin:2.3.2:jar (default-jar) @ github-maven-example ---
[INFO] Building jar: D:\qasibeat\temp-workspace\git\example\target\github-maven-example-0.1-SNAPSHOT.jar
[INFO] 
[INFO] --- maven-javadoc-plugin:2.9:jar (default) @ github-maven-example ---
[INFO] 
Loading source files for package com.github.maven.example...
Constructing Javadoc information...
Standard Doclet version 1.6.0_39
Building tree for all the packages and classes...
Generating D:/qasibeat/temp-workspace/git/example/target/apidocs\com/github/maven/example/\Widget.html...
Generating D:/qasibeat/temp-workspace/git/example/target/apidocs\com/github/maven/example/\package-frame.html...
Generating D:/qasibeat/temp-workspace/git/example/target/apidocs\com/github/maven/example/\package-summary.html...
Generating D:/qasibeat/temp-workspace/git/example/target/apidocs\com/github/maven/example/\package-tree.html...
Generating D:/qasibeat/temp-workspace/git/example/target/apidocs\constant-values.html...
Generating D:/qasibeat/temp-workspace/git/example/target/apidocs\com/github/maven/example/\class-use\Widget.html...
Generating D:/qasibeat/temp-workspace/git/example/target/apidocs\com/github/maven/example/\package-use.html...
Building index for all the packages and classes...
Generating D:/qasibeat/temp-workspace/git/example/target/apidocs\overview-tree.html...
Generating D:/qasibeat/temp-workspace/git/example/target/apidocs\index-all.html...
Generating D:/qasibeat/temp-workspace/git/example/target/apidocs\deprecated-list.html...
Building index for all classes...
Generating D:/qasibeat/temp-workspace/git/example/target/apidocs\allclasses-frame.html...
Generating D:/qasibeat/temp-workspace/git/example/target/apidocs\allclasses-noframe.html...
Generating D:/qasibeat/temp-workspace/git/example/target/apidocs\index.html...
Generating D:/qasibeat/temp-workspace/git/example/target/apidocs\help-doc.html...
Generating D:/qasibeat/temp-workspace/git/example/target/apidocs\stylesheet.css...
[INFO] Building jar: D:\qasibeat\temp-workspace\git\example\target\github-maven-example-0.1-SNAPSHOT-javadoc.jar
[INFO] 
[INFO] >>> maven-source-plugin:2.2.1:jar (default) @ github-maven-example >>>
[INFO] 
[INFO] <<< maven-source-plugin:2.2.1:jar (default) @ github-maven-example <<<
[INFO] 
[INFO] --- maven-source-plugin:2.2.1:jar (default) @ github-maven-example ---
[INFO] Building jar: D:\qasibeat\temp-workspace\git\example\target\github-maven-example-0.1-SNAPSHOT-sources.jar
[INFO] 
[INFO] --- maven-install-plugin:2.3.1:install (default-install) @ github-maven-example ---
[INFO] Installing D:\qasibeat\temp-workspace\git\example\target\github-maven-example-0.1-SNAPSHOT.jar to C:\Users\fold.m2\repository\com\github\kevinsawicki\github-maven-example\0.1-SNAPSHOT\github-maven-example-0.1-SNAPSHOT.jar
[INFO] Installing D:\qasibeat\temp-workspace\git\example\pom.xml to C:\Users\fold.m2\repository\com\github\kevinsawicki\github-maven-example\0.1-SNAPSHOT\github-maven-example-0.1-SNAPSHOT.pom
[INFO] Installing D:\qasibeat\temp-workspace\git\example\target\github-maven-example-0.1-SNAPSHOT-javadoc.jar to C:\Users\fold.m2\repository\com\github\kevinsawicki\github-maven-example\0.1-SNAPSHOT\github-maven-example-0.1-SNAPSHOT-javadoc.jar
[INFO] Installing D:\qasibeat\temp-workspace\git\example\target\github-maven-example-0.1-SNAPSHOT-sources.jar to C:\Users\fold.m2\repository\com\github\kevinsawicki\github-maven-example\0.1-SNAPSHOT\github-maven-example-0.1-SNAPSHOT-sources.jar
[INFO] 
[INFO] --- downloads-maven-plugin:0.6:upload (default) @ github-maven-example ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.146s
[INFO] Finished at: Wed Jun 19 02:58:57 VET 2013
[INFO] Final Memory: 8M/15M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.github:downloads-maven-plugin:0.6:upload (default) on project github-maven-example: Server 'github' not found in settings -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by icemagno** [comment]
Please update your demos and examples to not foolish us anymore.
Be clear about this in your main page and remove this plugin from Maven Central.

**Comment by thirdy** [comment]
started my journey here:

https://github.com/thirdy/github-maven-example

and ended up on this page.

**Comment by atatlisu** [comment]
so what is the solution ?

**Comment by ghostops5491** [comment]
I was also facing the same issue i just commented the whole plugin part and then it run fine for me .. hope that helps

**Comment by atatlisu** [comment]
I find out it just delete the plugin from <plugins> in pom.xml
